model_path: "EleutherAI/gpt-j-6B"
tokenizer_path: "EleutherAI/gpt-j-6B"
save_dir: "/mnt/nvme/home/alex/repos/rlhf/ckpts/gptj-rm-sft-IHP"

train_args:
  output_dir: "/mnt/nvme/home/alex/repos/rlhf/ckpts/gptj-rm-sft-IHP"
  num_train_epochs: 1
  logging_steps: 100
  save_strategy: "no"
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  warmup_steps: 100
  weight_decay: 0.01
  learning_rate: 1.0e-5
  save_total_limit: 1
  logging_dir: "./logs"
  fp16: False
  bf16: True
  evaluation_strategy: "epoch"

data_path: "Dahoas/sft_instruct_helpful_preferences"
trainer: "unmasked"