model_path: "EleutherAI/pythia-160m-deduped"
tokenizer_path: "EleutherAI/gpt-neox-20b"
save_dir: "/fsx/alex/ckpts/pythia/125M-response-full-static"

train_args:
  output_dir: "/fsx/alex/ckpts/pythia/125M-response-full-static"
  num_train_epochs: 1
  logging_steps: 100
  save_strategy: "epoch"
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  warmup_steps: 100
  weight_decay: 0.01
  learning_rate: 1.0e-5
  save_total_limit: 1
  logging_dir: "./logs"
  fp16: True
  evaluation_strategy: "epoch"

data_path: "Dahoas/static-hh"
trainer: "masked"